/*
 * This file is generated by jOOQ.
 */
package com.picnic.delivery.jooq.tables;

import java.time.OffsetDateTime;
import java.util.UUID;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Bookings extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    public static final Bookings BOOKINGS = new Bookings();

    public final TableField<Record, UUID> BOOKING_ID =
            createField(DSL.name("booking_id"), SQLDataType.UUID.nullable(false), this, "");

    public final TableField<Record, UUID> ORDER_ID =
            createField(DSL.name("order_id"), SQLDataType.UUID.nullable(false), this, "");

    public final TableField<Record, UUID> CUSTOMER_ID =
            createField(DSL.name("customer_id"), SQLDataType.UUID.nullable(false), this, "");

    public final TableField<Record, UUID> SLOT_ID =
            createField(DSL.name("slot_id"), SQLDataType.UUID.nullable(false), this, "");

    public final TableField<Record, String> STATE =
            createField(DSL.name("state"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    public final TableField<Record, OffsetDateTime> CREATED_AT =
            createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    public final TableField<Record, OffsetDateTime> UPDATED_AT =
            createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    private Bookings() {
        super(DSL.name("bookings"));
    }

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }
}
