/*
 * This file is generated by jOOQ.
 */
package com.picnic.delivery.jooq.tables;

import java.time.OffsetDateTime;
import java.util.UUID;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Slots extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    public static final Slots SLOTS = new Slots();

    public final TableField<Record, UUID> SLOT_ID =
            createField(DSL.name("slot_id"), SQLDataType.UUID.nullable(false), this, "");

    public final TableField<Record, String> POSTCODE =
            createField(DSL.name("postcode"), SQLDataType.CLOB.nullable(false), this, "");

    public final TableField<Record, UUID> WAREHOUSE_ID =
            createField(DSL.name("warehouse_id"), SQLDataType.UUID.nullable(false), this, "");

    public final TableField<Record, OffsetDateTime> START_AT =
            createField(DSL.name("start_at"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    public final TableField<Record, OffsetDateTime> END_AT =
            createField(DSL.name("end_at"), SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "");

    public final TableField<Record, Integer> TOTAL_CAPACITY =
            createField(DSL.name("total_capacity"), SQLDataType.INTEGER.nullable(false), this, "");

    public final TableField<Record, Integer> REMAINING_CAPACITY =
            createField(DSL.name("remaining_capacity"), SQLDataType.INTEGER.nullable(false), this, "");

    private Slots() {
        super(DSL.name("slots"));
    }

    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }
}
