/*
 * This file is generated by jOOQ.
 *
 * Codegen output is checked in so the service builds without a live database.
 * Regenerate with `mvn jooq-codegen:generate` after adding a migration.
 */
package com.picnic.delivery.jooq;

import com.picnic.delivery.jooq.tables.Bookings;
import com.picnic.delivery.jooq.tables.Slots;

@SuppressWarnings({"all"})
public class Tables {

    public static final Slots SLOTS = Slots.SLOTS;

    public static final Bookings BOOKINGS = Bookings.BOOKINGS;
}
